Repository neo4j-labs/llm-graph-builder, pull requests merged in 2024-10, with the labels that each got.

#800 Download Button For Chat Conversation
  frontend/src/components/ChatBot/Chatbot.tsx
  frontend/src/components/Layout/SideNav.tsx
  frontend/src/utils/Utils.ts
Labels: enhancement

#825 ragas changes for graph retrieval mode
  backend/example.env
  backend/src/QA_integration.py
Labels: improvement

#828 Document updates
  README.md
  backend/score.py
  docs/backend/backend_docs.adoc
Labels: documentation
