Repository neo4j-labs/llm-graph-builder, pull requests merged in 2024-11, with the labels that each got.

#876 Handled Nonetype error during global search.
  backend/src/QA_integration.py
Labels: bug

#870 Url changes and state management
  frontend/src/components/ChatBot/ChatOnlyComponent.tsx
  frontend/src/components/ChatBot/Chatbot.tsx
  frontend/src/components/ChatBot/ExpandedChatButtonContainer.tsx
  frontend/src/components/Layout/DrawerChatbot.tsx
  frontend/src/components/Layout/Header.tsx
  frontend/src/components/Layout/PageLayout.tsx
  frontend/src/components/Layout/SideNav.tsx
  frontend/src/context/UserMessages.tsx
  frontend/src/router.tsx
  frontend/src/types.ts
  frontend/src/utils/Constants.ts
Labels: enhancement

#898 re process feature state renaming
  backend/score.py
  backend/src/main.py
  docs/backend/backend_docs.adoc
  frontend/src/components/Content.tsx
  frontend/src/components/FileTable.tsx
  frontend/src/components/Popups/RetryConfirmation/Index.tsx
  frontend/src/utils/Utils.ts
Labels: improvement

#890 Community Counts after post processing
  backend/score.py
  backend/src/shared/constants.py
  frontend/src/components/BreakDownPopOver.tsx
  frontend/src/components/Content.tsx
  frontend/src/components/FileTable.tsx
  frontend/src/components/UI/CustomPopOver.tsx
Labels: bug

#899 added info to show 50 chunks processing
  frontend/src/components/Graph/GraphViewModal.tsx
  frontend/src/utils/Constants.ts
Labels: enhancement

#904 Delete query refined to delete all related nodes of file
  backend/score.py
  backend/src/graphDB_dataAccess.py
Labels: bug
