Repository neo4j-labs/llm-graph-builder, pull requests merged in 2024-06, with the labels that each got.

#424 wikipedia URL input
  backend/src/main.py
  backend/src/shared/common_fn.py
  frontend/src/App.css
  frontend/src/components/DropZone.tsx
  frontend/src/components/WikipediaModal.tsx
  frontend/src/utils/Utils.ts
Labels: enhancement

#422 speech and copy
  backend/src/chunkid_entities.py
  frontend/src/HOC/CustomModal.tsx
  frontend/src/components/Chatbot.tsx
  frontend/src/components/ConnectionModal.tsx
  frontend/src/components/Content.tsx
  frontend/src/components/DropZone.tsx
  frontend/src/components/GCSButton.tsx
  frontend/src/components/GCSModal.tsx
  frontend/src/components/IconsPlacement.tsx
  frontend/src/components/InfoModal.tsx
  frontend/src/components/Layout/SideNav.tsx
  frontend/src/components/S3Bucket.tsx
  frontend/src/components/S3Modal.tsx
  frontend/src/components/SchemaFromText.tsx
  frontend/src/components/WikipediaModal.tsx
  frontend/src/components/YoutubeButton.tsx
  frontend/src/components/YoutubeModal.tsx
  frontend/src/hooks/useSpeech.tsx
  frontend/src/types.ts
  frontend/src/utils/Constants.ts
Labels: enhancement

#428 UI polishing
  frontend/src/App.css
  frontend/src/components/ButtonWithToolTip.tsx
  frontend/src/components/GCSModal.tsx
  frontend/src/components/Layout/DrawerDropzone.tsx
  frontend/src/components/SettingModal.tsx
  frontend/src/components/WikipediaModal.tsx
  frontend/src/types.ts
  frontend/src/utils/Constants.ts
Labels: bug

#451 Adding sort rows on the table
  frontend/src/components/FileTable.tsx
Labels: enhancement

#459 Llm format change
  backend/score.py
  backend/src/QA_integration.py
  backend/src/shared/constants.py
  frontend/src/components/DropZone.tsx
  frontend/src/components/Dropdown.tsx
  frontend/src/components/FileTable.tsx
  frontend/src/components/GCSModal.tsx
  frontend/src/utils/Constants.ts
  frontend/src/utils/Utils.ts
Labels: bug

#473 Updated doc for the LLM_MODELS and GCS_FILE_CACHE
  README.md
  docker-compose.yml
  example.env
  frontend/example.env
Labels: documentation

#478 457 add schema before generate graph
  frontend/src/HOC/SettingModalHOC.tsx
  frontend/src/components/Content.tsx
  frontend/src/components/FileTable.tsx
  frontend/src/components/Layout/DrawerDropzone.tsx
  frontend/src/components/Layout/Header.tsx
  frontend/src/components/Layout/PageLayout.tsx
  frontend/src/components/Popups/Settings/SettingModal.tsx
  frontend/src/context/UsersFiles.tsx
  frontend/src/types.ts
  frontend/src/utils/Constants.ts
  frontend/src/utils/Utils.ts
Labels: enhancement

#485 Graph and vector search
  backend/score.py
  backend/src/QA_integration_new.py
  backend/src/shared/constants.py
  frontend/src/App.css
  frontend/src/assets/images/db-search.svg
  frontend/src/assets/images/graph-search.svg
  frontend/src/components/ChatBot/ChatModeToggle.tsx
  frontend/src/components/ChatBot/Chatbot.tsx
  frontend/src/components/ChatBot/ExpandedChatButtonContainer.tsx
  frontend/src/components/ChatBot/IconsPlacement.tsx
  frontend/src/components/ChatBot/Info/InfoModal.tsx
  frontend/src/components/Layout/SideNav.tsx
  frontend/src/context/UsersFiles.tsx
  frontend/src/services/GraphQuery.ts
  frontend/src/services/QnaAPI.ts
  frontend/src/types.ts
  frontend/src/utils/Constants.ts
Labels: enhancement
