Repository neo4j-labs/llm-graph-builder, pull requests merged in 2025-04, with the labels that each got.

#1221 Gemini 2.5 model addition
  backend/example.env
  frontend/src/utils/Constants.ts
Labels: enhancement

#1222 Updating status of failed upload file
  backend/score.py
Labels: bug

#1223 Llama4 model addition
  frontend/src/utils/Constants.ts
Labels: enhancement

#1224 New fixes
  frontend/src/components/Auth/Auth.tsx
  frontend/src/components/Content.tsx
  frontend/src/components/Graph/SchemaViz.tsx
  frontend/src/components/Layout/PageLayout.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/EntityExtractionSetting.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/GraphPattern.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/LoadExistingSchema.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/NewEntityExtractionSetting.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/PatternContainer.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/PredefinedSchemaDialog.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/SchemaFromTextDialog.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/index.tsx
  frontend/src/components/UI/SchemaSelectionPopup.tsx
  frontend/src/context/UsersFiles.tsx
  frontend/src/types.ts
  frontend/src/utils/Constants.ts
  frontend/src/utils/Utils.ts
Labels: bug, enhancement

#1233 New models addition
  backend/example.env
  frontend/src/utils/Constants.ts
Labels: enhancement

#1248 Validation for tuple schema
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/EntityExtractionSetting.tsx
  frontend/src/components/Popups/GraphEnhancementDialog/EnitityExtraction/GraphPattern.tsx
  frontend/src/components/Popups/Settings/SchemaFromText.tsx
  frontend/src/components/UI/CustomCheckBox.tsx
  frontend/src/components/UI/ShowAll.tsx
Labels: improvement
